;; Exercise 1.9: Each of the following two procedures defines
;; a method for adding two positive integers in terms of the
;; procedures inc , which increments its argument by 1, and dec ,
;; which decrements its argument by 1.
(define (+ a b)
  (if (= a 0) b (inc (+ (dec a) b))))
(define (+ a b)
  (if (= a 0) b (+ (dec a) (inc b))))
;; Using the substitution model, illustrate the process generated by
;; each procedure in evaluating (+ 4 5) . Are these processes itera-
;; tive or recursive?

(if (= 4 0) 5 (inc (+ (dec 4) 5)))
(if false 5 (inc (+ 3 5)))
(inc (+ (dec 3) 5))
(inc (inc (+ (dec 2) 5)))
(inc (inc (inc (+ (dec 1) 5))))
(inc (inc (inc (inc (+ (dec 0) 5)))))
(inc (inc (inc (inc 5))))
(inc (inc (inc 6)))
(inc (inc 7))
(inc 8)
9

(if (= 4 0) 5 (+ (dec 4) (inc 5)))
(if false 5 (+ 3 6))
(if (= 3 0) 6 (+ (dec 3) (inc 6)))
(if false 6 (+ 2 7))
(if (= 2 0) 7 (+ (dec 2) (inc 7)))
(if false 7 (+ 2 7))
(if (= 1 0) 8 (+ (dec 1) (inc 8)))
(if false 8 (+ 1 8))
(if (= 0 0) 9 (+ (dec 0) (inc 9)))
(if true 9 (+ 0 9))
9

They are both recursive precedures. The former is a recursive process. The
latter is a iterative process.
