;; Exercise 1.14: Draw the tree illustrating the process generated by
;; the count-change procedure of Section 1.2.2 in making change for
;; 11 cents. What are the orders of growth of the space and number of
;; steps used by this process as the amount to be changed increases?

;; Tree level 1
(count-change 11)
(cc 11 5)
(+ (cc 11 4) (cc (- 11 50) 5))

;; level 1.1
(cc 11 4)
(+ (cc 11 3) (cc (- 11 25) 4))

;; level 1.2
(cc (- 11 50) 5)
0

;; level 1.1.1
(cc 11 3)
(+ (cc 11 2) (cc (- 11 10) 3))

;; level 1.1.2
(cc (- 11 25) 4)
0

;; level 1.1.1.1
(cc 11 2)
(+ (cc 11 1) (cc (- 11 5) 2))

;; level 1.1.1.2
(cc (- 11 10) 3)
(+ (cc 1 2) (cc (- 1 10) 3))

;; level 1.1.1.1.1
(cc 11 1)
(+ (cc 11 0) (cc (- 11 1) 1))

;; level 1.1.1.1.2
(cc (- 11 5) 2)
(+ (cc 6 1) (cc (- 11 5) 2))

;; level 1.1.1.2.1
(cc 1 2)
(+ (cc 1 1) (cc (- 1 5) 3))

;; level 1.1.1.2.2
(cc (- 1 10) 3)
0

;; level 1.1.1.1.1.1
(cc 11 0)
0

;; level 1.1.1.1.1.2
(cc 10 1)
(+ (cc 10 0) (cc (- 10 1) 1))

;; Got tired of writing stuff out here.
;; Pretty tree copied from http://community.schemewiki.org/?sicp-ex-1.14

 ;;                                 11 => 50 25 10 5 1
 ;;                                       4|0
 ;;                             +----------+---------+
 ;;                             |                    |
 ;;                        11 => 25 10 5 1      -39 => 50 25 10 5 1
 ;;                            4|0
 ;;                    +--------+-------+
 ;;                    |                |
 ;;               11 => 10 5 1    -14 => 25 10 5 1
 ;;                   3|1
 ;;            +-------+--------------------------------------+
 ;;            |                                              |
 ;;      11 => 5 1                                       1=> 10 5 1
 ;;           1|2                                            1|0
 ;;    +-------+-------+                                 +----+---------+
 ;;    |               |                                 |              |
 ;; 11=> 1          6 => 5 1                           1=> 5 1      -9 => 10 5 1
 ;;                   1|1                               1|0
 ;;           +--------+----+                      +-----+---+
 ;;           |             |                      |         |
 ;;        6 => 1        1 => 5 1               1 => 1     -4=> 5 1
 ;;                        1|0
 ;;                    +----+----+
 ;;                    |         |
 ;;                1 => 1     -4=> 5 1

;; Space is determined by the depth of the tree as the only memory requirement
;; is remembering the stack. Between O(1) O(n) and O(n^e) the space required is
;; linear O(n).

;; Steps is determined by the increase of nodes at each further depth.
;; The number of nodes at each depth (very) roughly doubles. The number of steps
;; is exponential O(n^e).

